// pages/icon/icon.js
Page({
    data: {
        iconData: [{
            "icon_name": "warn",
            "icon_text": ".icon-warn"
        }, {
            "icon_name": "more_android",
            "icon_text": ".icon-moreandroid"
        }, {
            "icon_name": "home",
            "icon_text": ".icon-home"
        }, {
            "icon_name": "home_fill",
            "icon_text": ".icon-homefill"
        }, {
            "icon_name": "sort",
            "icon_text": ".icon-sort"
        }, {
            "icon_name": "female",
            "icon_text": ".icon-female"
        }, {
            "icon_name": "支付宝钱包",
            "icon_text": ".icon-rectangle390"
        }, {
            "icon_name": "telephone",
            "icon_text": ".icon-telephone"
        }, {
            "icon_name": "back",
            "icon_text": ".icon-back"
        }, {
            "icon_name": "less",
            "icon_text": ".icon-less"
        }, {
            "icon_name": "more_unfold",
            "icon_text": ".icon-moreunfold"
        }, {
            "icon_name": "more",
            "icon_text": ".icon-more"
        }, {
            "icon_name": "selected",
            "icon_text": ".icon-selected"
        }, {
            "icon_name": "warning",
            "icon_text": ".icon-warning"
        }, {
            "icon_name": "wrong",
            "icon_text": ".icon-wrong"
        }, {
            "icon_name": "3.1图文详情",
            "icon_text": ".icon-31tuwenxiangqing"
        }, {
            "icon_name": "文本编辑_填充",
            "icon_text": ".icon-wenbenbianjitianchong"
        }, {
            "icon_name": "文本编辑",
            "icon_text": ".icon-wenbenbianji"
        }, {
            "icon_name": "my",
            "icon_text": ".icon-my"
        }, {
            "icon_name": "my_fill",
            "icon_text": ".icon-myfill"
        }, {
            "icon_name": "warning",
            "icon_text": ".icon-warning1"
        }, {
            "icon_name": "方形未选中",
            "icon_text": ".icon-fangxingweixuanzhong"
        }, {
            "icon_name": "方形选中-fill",
            "icon_text": ".icon-fangxingxuanzhongfill"
        }, {
            "icon_name": "方形选中",
            "icon_text": ".icon-fangxingxuanzhong"
        }, {
            "icon_name": "关闭1",
            "icon_text": ".icon-guanbi1"
        }, {
            "icon_name": "关闭2-fill",
            "icon_text": ".icon-guanbi2fill"
        }, {
            "icon_name": "关闭2",
            "icon_text": ".icon-guanbi2"
        }, {
            "icon_name": "加号1",
            "icon_text": ".icon-jiahao1"
        }, {
            "icon_name": "减号",
            "icon_text": ".icon-jianhao"
        }, {
            "icon_name": "提示-fill",
            "icon_text": ".icon-tishifill"
        }, {
            "icon_name": "提示",
            "icon_text": ".icon-tishi"
        }, {
            "icon_name": "问号-fill",
            "icon_text": ".icon-wenhaofill"
        }, {
            "icon_name": "问号",
            "icon_text": ".icon-wenhao"
        }, {
            "icon_name": "选择",
            "icon_text": ".icon-xuanze"
        }, {
            "icon_name": "圆形未选中",
            "icon_text": ".icon-yuanxingweixuanzhong"
        }, {
            "icon_name": "圆形选中-fill",
            "icon_text": ".icon-yuanxingxuanzhongfill"
        }, {
            "icon_name": "圆形选中",
            "icon_text": ".icon-yuanxingxuanzhong"
        }, {
            "icon_name": "标星-fill",
            "icon_text": ".icon-biaoxingfill"
        }, {
            "icon_name": "标星",
            "icon_text": ".icon-biaoxing"
        }, {
            "icon_name": "购物车-fill",
            "icon_text": ".icon-gouwuchefill"
        }, {
            "icon_name": "购物车",
            "icon_text": ".icon-gouwuche"
        }, {
            "icon_name": "卡片形式",
            "icon_text": ".icon-qiapianxingshi"
        }, {
            "icon_name": "留言-fill",
            "icon_text": ".icon-liuyanfill"
        }, {
            "icon_name": "留言",
            "icon_text": ".icon-liuyan"
        }, {
            "icon_name": "时钟-fill",
            "icon_text": ".icon-shizhongfill"
        }, {
            "icon_name": "时钟",
            "icon_text": ".icon-shizhong"
        }, {
            "icon_name": "坐标-fill",
            "icon_text": ".icon-zuobiaofill"
        }, {
            "icon_name": "坐标",
            "icon_text": ".icon-zuobiao"
        }, {
            "icon_name": "购物车",
            "icon_text": ".icon-gouwuche1"
        }, {
            "icon_name": "购物车添加",
            "icon_text": ".icon-gouwuchetianjia"
        }, {
            "icon_name": "聚收藏",
            "icon_text": ".icon-jushoucang"
        }, {
            "icon_name": "mobile",
            "icon_text": ".icon-mobile"
        }, {
            "icon_name": "免",
            "icon_text": ".icon-mian"
        }, {
            "icon_name": "图片加载失败-02",
            "icon_text": ".icon-tupianjiazaishibai02"
        }, {
            "icon_name": "聚收藏gift",
            "icon_text": ".icon-jushoucanggift"
        }, {
            "icon_name": "待付款",
            "icon_text": ".icon-icon"
        }, {
            "icon_name": "complete",
            "icon_text": ".icon-wancheng"
        }, {
            "icon_name": "comment_fill",
            "icon_text": ".icon-commentfill"
        }, {
            "icon_name": "round",
            "icon_text": ".icon-round"
        }, {
            "icon_name": "male",
            "icon_text": ".icon-male"
        }, {
            "icon_name": "more",
            "icon_text": ".icon-more1"
        }, {
            "icon_name": "二维码",
            "icon_text": ".icon-erweima"
        }, {
            "icon_name": "收起菜单",
            "icon_text": ".icon-shouqicaidan"
        }, {
            "icon_name": "展开菜单",
            "icon_text": ".icon-zhankaicaidan"
        }, {
            "icon_name": "warn",
            "icon_text": ".icon-warn1"
        }, {
            "icon_name": "cards",
            "icon_text": ".icon-cards"
        }, {
            "icon_name": "cards-outline",
            "icon_text": ".icon-cards-outline"
        }, {
            "icon_name": "日历1",
            "icon_text": ".icon-rili"
        }, {
            "icon_name": "日历2",
            "icon_text": ".icon-rili1"
        }, {
            "icon_name": "日历4",
            "icon_text": ".icon-rili2"
        }, {
            "icon_name": "日历3",
            "icon_text": ".icon-rili3"
        }, {
            "icon_name": "日历5",
            "icon_text": ".icon-rili4"
        }, {
            "icon_name": "日历7",
            "icon_text": ".icon-rili5"
        }, {
            "icon_name": "日历8",
            "icon_text": ".icon-rili6"
        }, {
            "icon_name": "日历11",
            "icon_text": ".icon-rili7"
        }, {
            "icon_name": "日历9",
            "icon_text": ".icon-rili8"
        }, {
            "icon_name": "日历12",
            "icon_text": ".icon-rili9"
        }, {
            "icon_name": "日历10",
            "icon_text": ".icon-rili10"
        }, {
            "icon_name": "日历13",
            "icon_text": ".icon-rili11"
        }, {
            "icon_name": "日历14",
            "icon_text": ".icon-rili12"
        }, {
            "icon_name": "日历6",
            "icon_text": ".icon-rili13"
        }, {
            "icon_name": "日历15",
            "icon_text": ".icon-rili14"
        }, {
            "icon_name": "日历17",
            "icon_text": ".icon-rili15"
        }, {
            "icon_name": "日历16",
            "icon_text": ".icon-rili16"
        }, {
            "icon_name": "日历18",
            "icon_text": ".icon-rili17"
        }, {
            "icon_name": "日历19",
            "icon_text": ".icon-rili18"
        }, {
            "icon_name": "日历21",
            "icon_text": ".icon-rili19"
        }, {
            "icon_name": "日历20",
            "icon_text": ".icon-rili20"
        }, {
            "icon_name": "日历24",
            "icon_text": ".icon-rili21"
        }, {
            "icon_name": "日历22",
            "icon_text": ".icon-rili22"
        }, {
            "icon_name": "日历25",
            "icon_text": ".icon-rili23"
        }, {
            "icon_name": "日历23",
            "icon_text": ".icon-rili24"
        }, {
            "icon_name": "日历27",
            "icon_text": ".icon-rili25"
        }, {
            "icon_name": "日历26",
            "icon_text": ".icon-rili26"
        }, {
            "icon_name": "日历29",
            "icon_text": ".icon-rili27"
        }, {
            "icon_name": "日历28",
            "icon_text": ".icon-rili28"
        }, {
            "icon_name": "日历30",
            "icon_text": ".icon-rili29"
        }, {
            "icon_name": "资料库",
            "icon_text": ".icon-ziliaoku"
        }, {
            "icon_name": "微信",
            "icon_text": ".icon-weixin"
        }, {
            "icon_name": "301加-方框",
            "icon_text": ".icon-jia-fangkuang"
        }, {
            "icon_name": "301加-线性方框",
            "icon_text": ".icon-jia-xianxingfangkuang"
        }, {
            "icon_name": "302减-方框",
            "icon_text": ".icon-jian-fangkuang"
        }, {
            "icon_name": "302减-线性方框",
            "icon_text": ".icon-jian-xianxingfangkuang"
        }, {
            "icon_name": "304错误、关闭、取消-线性方框",
            "icon_text": ".icon-cuowuguanbiquxiao-xianxingfangkuang"
        }, {
            "icon_name": "304错误、关闭、取消-方框",
            "icon_text": ".icon-cuowuguanbiquxiao-fangkuang"
        }, {
            "icon_name": "333加载loading-B",
            "icon_text": ".icon-jiazailoading-B"
        }, {
            "icon_name": "401位置",
            "icon_text": ".icon-weizhi"
        }, {
            "icon_name": "赞2",
            "icon_text": ".icon-zan"
        }, {
            "icon_name": "赞",
            "icon_text": ".icon-zan1"
        }, {
            "icon_name": "扫一扫",
            "icon_text": ".icon-richscan_icon"
        }, {
            "icon_name": "待收货",
            "icon_text": ".icon-daishouhuo"
        }, {
            "icon_name": "售后退款",
            "icon_text": ".icon-shouhoutuikuan"
        }, {
            "icon_name": "客服",
            "icon_text": ".icon-kefu"
        }, {
            "icon_name": "箭头 上",
            "icon_text": ".icon-jiantoushang"
        }, {
            "icon_name": "箭头 右",
            "icon_text": ".icon-jiantouyou"
        }, {
            "icon_name": "箭头 下",
            "icon_text": ".icon-jiantouxia"
        }, {
            "icon_name": "搜索",
            "icon_text": ".icon-sousuo"
        }, {
            "icon_name": "tab角标",
            "icon_text": ".icon-tabguanbi"
        }, {
            "icon_name": "地址管理",
            "icon_text": ".icon-dizhiguanli"
        }, {
            "icon_name": "待收货",
            "icon_text": ".icon-daishouhuo1"
        }, {
            "icon_name": "未使用",
            "icon_text": ".icon-weishiyong"
        }, {
            "icon_name": "签到",
            "icon_text": ".icon-qiandao"
        }, {
            "icon_name": "转出",
            "icon_text": ".icon-zhuanchu"
        }, {
            "icon_name": "转入",
            "icon_text": ".icon-zhuanru"
        }, {
            "icon_name": "Loading",
            "icon_text": ".icon-Loading"
        }, {
            "icon_name": "常用购票人／编辑32",
            "icon_text": ".icon-changyonggoupiaorenbianji"
        }, {
            "icon_name": "loading",
            "icon_text": ".icon-loading1"
        }, {
            "icon_name": "删除",
            "icon_text": ".icon-shanchu"
        }, {
            "icon_name": "编辑",
            "icon_text": ".icon-bianji"
        }, {
            "icon_name": "权限审批",
            "icon_text": ".icon-quanxianshenpi"
        }, {
            "icon_name": "icon_预览",
            "icon_text": ".icon-icon_yulan"
        }, {
            "icon_name": "编辑",
            "icon_text": ".icon-bianji1"
        }, {
            "icon_name": "打开",
            "icon_text": ".icon-dakai"
        }, {
            "icon_name": "英文",
            "icon_text": ".icon-yingwen"
        }, {
            "icon_name": "中文",
            "icon_text": ".icon-zhongwen"
        }, {
            "icon_name": "密文",
            "icon_text": ".icon-miwen"
        }, {
            "icon_name": "下一步",
            "icon_text": ".icon-xiayibu"
        }, {
            "icon_name": "上一步",
            "icon_text": ".icon-shangyibu"
        }, {
            "icon_name": "控件选中",
            "icon_text": ".icon-kongjianxuanzhong"
        }, {
            "icon_name": "控件未选",
            "icon_text": ".icon-kongjianweixuan"
        }, {
            "icon_name": "控件已选",
            "icon_text": ".icon-kongjianyixuan"
        }, {
            "icon_name": "方块+",
            "icon_text": ".icon-fangkuai"
        }, {
            "icon_name": "方块-",
            "icon_text": ".icon-fangkuai-"
        }, {
            "icon_name": "下一步",
            "icon_text": ".icon-xiayibu1"
        }, {
            "icon_name": "上一步",
            "icon_text": ".icon-shangyibu1"
        }, {
            "icon_name": "向下占行",
            "icon_text": ".icon-xiangxiazhanhang"
        }, {
            "icon_name": "向上占行",
            "icon_text": ".icon-xiangshangzhanhang"
        }, {
            "icon_name": "图片加载失败",
            "icon_text": ".icon-tupianjiazaishibai"
        }, {
            "icon_name": "frown",
            "icon_text": ".icon-frown"
        }, {
            "icon_name": "meh",
            "icon_text": ".icon-meh"
        }, {
            "icon_name": "smile",
            "icon_text": ".icon-smile"
        }, {
            "icon_name": "earth",
            "icon_text": ".icon-earth"
        }, {
            "icon_name": "calendar",
            "icon_text": ".icon-calendar"
        }, {
            "icon_name": "vertical right",
            "icon_text": ".icon-verticalright"
        }, {
            "icon_name": "vertical left",
            "icon_text": ".icon-verticalleft"
        }, {
            "icon_name": "fullscreen",
            "icon_text": ".icon-fullscreen"
        }, {
            "icon_name": "fullscreen-exit",
            "icon_text": ".icon-fullscreen-exit"
        }, {
            "icon_name": "download",
            "icon_text": ".icon-download"
        }, {
            "icon_name": "缩小",
            "icon_text": ".icon-suoxiao"
        }, {
            "icon_name": "放大",
            "icon_text": ".icon-fangda"
        }, {
            "icon_name": "comment",
            "icon_text": ".icon-comment"
        }, {
            "icon_name": "round_check_fill",
            "icon_text": ".icon-round_check_fill"
        }, {
            "icon_name": "BMP",
            "icon_text": ".icon-BMP"
        }, {
            "icon_name": "GIF",
            "icon_text": ".icon-GIF"
        }, {
            "icon_name": "JPG",
            "icon_text": ".icon-JPG"
        }, {
            "icon_name": "PNG",
            "icon_text": ".icon-PNG"
        }, {
            "icon_name": "未知格式",
            "icon_text": ".icon-weizhigeshi"
        }, {
            "icon_name": "云端下载",
            "icon_text": ".icon-yunduanxiazai"
        }, {
            "icon_name": "云端上传",
            "icon_text": ".icon-yunduanshangchuan"
        }, {
            "icon_name": "点",
            "icon_text": ".icon-dian"
        }, {
            "icon_name": "frown-fill",
            "icon_text": ".icon-frown-fill"
        }, {
            "icon_name": "Dollar-circle-fill",
            "icon_text": ".icon-Dollar-circle-fill"
        }, {
            "icon_name": "meh-fill",
            "icon_text": ".icon-meh-fill"
        }, {
            "icon_name": "smile-fill",
            "icon_text": ".icon-smile-fill"
        }, {
            "icon_name": "YUAN-circle-fill",
            "icon_text": ".icon-YUAN-circle-fill"
        }, {
            "icon_name": "IE-circle-fill",
            "icon_text": ".icon-IE-circle-fill"
        }, {
            "icon_name": "twitter-circle-fill",
            "icon_text": ".icon-twitter-circle-fill"
        }, {
            "icon_name": "taobao-circle-fill",
            "icon_text": ".icon-taobao-circle-fill"
        }, {
            "icon_name": "weibo-circle-fill",
            "icon_text": ".icon-weibo-circle-fill"
        }, {
            "icon_name": "zhihu-circle-fill",
            "icon_text": ".icon-zhihu-circle-fill"
        }, {
            "icon_name": "alipay-square-fill",
            "icon_text": ".icon-alipay-square-fill"
        }, {
            "icon_name": "facebook-fill",
            "icon_text": ".icon-facebook-fill"
        }, {
            "icon_name": "匿名用户",
            "icon_text": ".icon-nimingyonghu"
        }, {
            "icon_name": "角标选中",
            "icon_text": ".icon-jiaobiaoxuanzhong"
        }, {
            "icon_name": "个人信息_o",
            "icon_text": ".icon-gerenxinxi_o"
        }, {
            "icon_name": "软件开发包",
            "icon_text": ".icon-ruanjiankaifabao"
        }, {
            "icon_name": "warn",
            "icon_text": ".icon-warn2"
        }, {
            "icon_name": "编辑",
            "icon_text": ".icon-edit-line"
        }, {
            "icon_name": "预约",
            "icon_text": ".icon-yuyue"
        }, {
            "icon_name": "caret-down",
            "icon_text": ".icon-caret-down"
        }, {
            "icon_name": "backward",
            "icon_text": ".icon-backward"
        }, {
            "icon_name": "caret-up",
            "icon_text": ".icon-caret-up"
        }, {
            "icon_name": "caret-right",
            "icon_text": ".icon-caret-right"
        }, {
            "icon_name": "caret-left",
            "icon_text": ".icon-caret-left"
        }, {
            "icon_name": "fast-backward",
            "icon_text": ".icon-fast-backward"
        }, {
            "icon_name": "forward",
            "icon_text": ".icon-forward"
        }, {
            "icon_name": "fast-forward",
            "icon_text": ".icon-fast-forward"
        }, {
            "icon_name": "电表_实体",
            "icon_text": ".icon-dianbiao_shiti"
        }, {
            "icon_name": "水表_实体",
            "icon_text": ".icon-shuibiao_shiti"
        }, {
            "icon_name": "摄像头_实体",
            "icon_text": ".icon-shexiangtou_shiti"
        }, {
            "icon_name": "摄像头",
            "icon_text": ".icon-shexiangtou"
        }, {
            "icon_name": "声音_实体",
            "icon_text": ".icon-shengyin_shiti"
        }, {
            "icon_name": "声音开",
            "icon_text": ".icon-shengyinkai"
        }, {
            "icon_name": "声音无",
            "icon_text": ".icon-shengyinwu"
        }, {
            "icon_name": "声音静音",
            "icon_text": ".icon-shengyinjingyin"
        }, {
            "icon_name": "addition_fill",
            "icon_text": ".icon-addition_fill"
        }, {
            "icon_name": "addition",
            "icon_text": ".icon-addition"
        }, {
            "icon_name": "addpeople_fill",
            "icon_text": ".icon-addpeople_fill"
        }, {
            "icon_name": "addpeople",
            "icon_text": ".icon-addpeople"
        }, {
            "icon_name": "camera_fill",
            "icon_text": ".icon-camera_fill"
        }, {
            "icon_name": "camera",
            "icon_text": ".icon-camera"
        }, {
            "icon_name": "clock_fill",
            "icon_text": ".icon-clock_fill"
        }, {
            "icon_name": "clock",
            "icon_text": ".icon-clock"
        }, {
            "icon_name": "close",
            "icon_text": ".icon-close"
        }, {
            "icon_name": "coordinates_fill",
            "icon_text": ".icon-coordinates_fill"
        }, {
            "icon_name": "coordinates",
            "icon_text": ".icon-coordinates"
        }, {
            "icon_name": "coupons_fill",
            "icon_text": ".icon-coupons_fill"
        }, {
            "icon_name": "coupons",
            "icon_text": ".icon-coupons"
        }, {
            "icon_name": "createtask_fill",
            "icon_text": ".icon-createtask_fill"
        }, {
            "icon_name": "createtask",
            "icon_text": ".icon-createtask"
        }, {
            "icon_name": "delete_fill",
            "icon_text": ".icon-delete_fill"
        }, {
            "icon_name": "delete",
            "icon_text": ".icon-delete1"
        }, {
            "icon_name": "dynamic_fill",
            "icon_text": ".icon-dynamic_fill"
        }, {
            "icon_name": "dynamic",
            "icon_text": ".icon-dynamic"
        }, {
            "icon_name": "editor",
            "icon_text": ".icon-editor"
        }, {
            "icon_name": "eit",
            "icon_text": ".icon-eit"
        }, {
            "icon_name": "flag_fill",
            "icon_text": ".icon-flag_fill"
        }, {
            "icon_name": "flag",
            "icon_text": ".icon-flag"
        }, {
            "icon_name": "headlines_fill",
            "icon_text": ".icon-headlines_fill"
        }, {
            "icon_name": "headlines",
            "icon_text": ".icon-headlines"
        }, {
            "icon_name": "label",
            "icon_text": ".icon-label"
        }, {
            "icon_name": "label_fill",
            "icon_text": ".icon-label_fill"
        }, {
            "icon_name": "lock_fill",
            "icon_text": ".icon-lock_fill"
        }, {
            "icon_name": "lock",
            "icon_text": ".icon-lock"
        }, {
            "icon_name": "mail",
            "icon_text": ".icon-mail"
        }, {
            "icon_name": "mail_fill",
            "icon_text": ".icon-mail_fill"
        }, {
            "icon_name": "manage_fill",
            "icon_text": ".icon-manage_fill"
        }, {
            "icon_name": "manage",
            "icon_text": ".icon-manage"
        }, {
            "icon_name": "mobilephone_fill",
            "icon_text": ".icon-mobilephone_fill"
        }, {
            "icon_name": "mobilephone",
            "icon_text": ".icon-mobilephone"
        }, {
            "icon_name": "offline_fill",
            "icon_text": ".icon-offline_fill"
        }, {
            "icon_name": "offline",
            "icon_text": ".icon-offline"
        }, {
            "icon_name": "praise_fill",
            "icon_text": ".icon-praise_fill"
        }, {
            "icon_name": "praise",
            "icon_text": ".icon-praise"
        }, {
            "icon_name": "qrcode_fill",
            "icon_text": ".icon-qrcode_fill"
        }, {
            "icon_name": "qrcode",
            "icon_text": ".icon-qrcode"
        }, {
            "icon_name": "service_fill",
            "icon_text": ".icon-service_fill"
        }, {
            "icon_name": "service",
            "icon_text": ".icon-service"
        }, {
            "icon_name": "setup_fill",
            "icon_text": ".icon-setup_fill"
        }, {
            "icon_name": "setup",
            "icon_text": ".icon-setup"
        }, {
            "icon_name": "unlock_fill",
            "icon_text": ".icon-unlock_fill"
        }, {
            "icon_name": "unlock",
            "icon_text": ".icon-unlock1"
        }],
    },
    onLoad() {
        console.log(typeof this.data.iconData)
        console.log(this.data.iconData.length)
    }
})